config/routes.rb
Photogur::Application.routes.draw do

  resources :pictures
 root :to => "pictures#index"

  

   
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :artist, :title, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController


	def index
		
	@picture = Picture.all

	end


	def show
 	 @picture = Picture.find(params[:id])


	end

	def new
		@picture = Picture.new
	end


	def create
		
		@picture = Picture.new(params[:picture])

		if @picture.save
			redirect_to pictures_url
		else 
			render :new

		end
		#render :text => "Saving a picture. URL: #{params[:url]}, Title: #{params[:title]}, Artist:#{params[:artist]}"

	end

	def edit
		@picture = Picture.find(params[:id])
	end

	def update 
		@picture = Picture.find(params[:id])

		if @picture.update_attributes(params[:picture])
			redirect_to "/pictures/#{@picture.id}"
		else 
			render :edit
		end

	end

	def destroy 
		@picture = Picture.find(params[:id])
		@picture.destroy
		redirect_to pictures_url
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/edit.html.erb
<h1>Edit Picture</h1>

<p>
  <%= link_to "Back", @picture %>
</p>

<%= form_for @picture do |f| %>
  <p>
    <%= f.label "artist" %><br>
    <%= f.text_field "artist" %>
  </p>
  <p>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </p>
  <p>
    <%= f.label "url" %><br>
    <%= f.text_field "url" %>
  </p>
  <p>
    <%= submit_tag "Save" %>
  </p>
<% end %>

app/views/pictures/index.html.erb
<h1>Pictures (<%= @picture.length %>)</h1>
<%= link_to "New Picture", "/pictures/new" %>

<% @picture.each do |picture| %>
  <p><%= picture[:title] %>, <%= picture[:artist] %></p>
  <img src="<%= picture[:url] %>">
<% end %>

app/views/pictures/new.html.erb
<h1> Add a picture </h1>
<%= link_to "Back to Pictures", pictures_url%>

<%= form_for @picture do |f| %>
<p>
<%= f.label "artist" %> <br>
<%= f.text_field "artist" %>
</p>

<p>
<%= f.label "title" %><br>
<%= f.text_field "title"%>
</p>

<p>
<%= f.label "url" %><br>
<%= f.text_field "url"%>
</p>


<p>
<%= f.submit "Save" %>
</p>

<% end %>
<!-- 
<form action = "/pictures" method = "POST" >
	<p> 

		<label> Artist </label> <br>
		<input type = "text" name = "artist" />
	</p>
	<p> 

		<label> Title </label> <br>
		<input type = "text" name = "title" />
	</p>
	<p>
		<label> URL </label> <br>
		<input type = "text" name = "url" />
	</p>
	<p>
		<input type = "submit"/>
	</p>

</form>
 -->

app/views/pictures/show.html.erb
<%= link_to "Back to Pictures", pictures_url %> | <%= link_to "Edit", edit_picture_path(@picture) %> | <%= link_to "Delete", @picture, :confirm => "Are you sure you want to delete this picture?", :method => :delete %>

<p> <%=@picture[:title]%>, <%= @picture[:artist]%> </p>
<img src = "<%= @picture[:url] %>">